### ISSUE TITLE
Undesired behaviour when the minimum event rate for dynamic sampling is never reached

### ISSUE THREAD

**Issue by niligulmohar** [honeycombio/dynsampler-go#16] opened 2020-08-18 13:00 UTC
This is a follow-up of honeycombio/honeycomb-kubernetes-agent#81.

When using dynamic sampling for a log watcher where the event rate never reaches the minimum rate of `dynsampler.AvgSampleWithMin` the watcher will use the target sample rate as a static sample rate forever.

If the minimum sample rate is reached once, and `dynsampler.AvgSampleWithMin.updateMaps` returns normally, `haveData` will be set. After that all events will be kept when the event rate drops below minimum, instead of sampling at the target sample rate.

I think it would be better for the watcher to fall back to keeping all events, even if the minimum event rate is never reached.

**Comment by MikeGoldsmith** [comment] 2021-09-23 11:04
Closing as a duplicate of #7.

**Closed by MikeGoldsmith** 2021-09-23 11:04 UTC
Labels: type: bug, status: help wanted
